# Generated by Django 5.1 on 2026-10-08 19:33

import django.db.models.deletion
import django.utils.timezone
import meetings.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConvAI', '0097_jobs_and_online_seams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=80, unique=True)),
                ('event', models.CharField(max_length=40)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=meetings.models._public_id, max_length=24, unique=True)),
                ('nonce', models.CharField(default=meetings.models._nonce, max_length=48)),
                ('invitee', models.CharField(choices=[('caregiver', 'Caregiver'), ('client', 'Client'), ('other', 'Other')], default='caregiver', max_length=12)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('record_allowed', models.BooleanField(default=True)),
                ('principal', models.CharField(choices=[('link', 'Link')], default='link', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=120)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ConvAI.caregiver')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_invites', to='ConvAI.meeting')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ConvAI.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=12)),
                ('to_masked', models.CharField(blank=True, default='', max_length=80)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='meetings.meetinginvite')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended')], default='live', max_length=8)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, default='', max_length=60)),
                ('room_sid', models.CharField(blank=True, default='', max_length=64)),
                ('auto_admit', models.BooleanField(default=False)),
                ('recording_enabled', models.BooleanField(default=True)),
                ('recording_state', models.CharField(choices=[('off', 'Not recording'), ('starting', 'Starting'), ('on', 'Recording'), ('lost', 'Recorder lost'), ('stopped', 'Stopped')], default='off', max_length=10)),
                ('recorder_seen_at', models.DateTimeField(blank=True, null=True)),
                ('recorder_dispatches', models.PositiveSmallIntegerField(default=0)),
                ('last_human_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_sessions', to='ConvAI.meeting')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ConvAI.callrecording')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LobbyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('admitted', 'Admitted'), ('denied', 'Turned away'), ('left', 'Left')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ConvAI.meeting')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_entries', to='meetings.meetinginvite')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=96)),
                ('participant_sid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('kind', models.CharField(choices=[('staff', 'Staff'), ('invitee', 'Invitee'), ('agent', 'Agent')], max_length=8)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('left_reason', models.CharField(blank=True, default='', max_length=40)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meetings.meetinginvite')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('scribe', 'Recorder'), ('interviewer', 'Interviewer'), ('assistant', 'Assistant')], max_length=12)),
                ('state', models.CharField(choices=[('dispatched', 'Connecting'), ('running', 'Running'), ('paused', 'Paused'), ('finished', 'Finished'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='dispatched', max_length=12)),
                ('respondent_identity', models.CharField(blank=True, default='', max_length=96)),
                ('respondent_name', models.CharField(blank=True, default='', max_length=80)),
                ('controller_identity', models.CharField(blank=True, default='', max_length=96)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('agent_identity', models.CharField(blank=True, default='', max_length=96)),
                ('dispatch_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_at', models.DateTimeField(blank=True, null=True)),
                ('answers_saved', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ConvAI.protocol')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.CharField(blank=True, choices=[('', 'Use the .env default'), ('1', 'On'), ('0', 'Off')], default='', help_text='Off by default. While off, online meetings cannot be booked or joined; existing ones stay readable.', max_length=1)),
                ('record_by_default', models.BooleanField(default=True, help_text="Record each participant's audio (never video) unless switched off for a meeting. Recordings are transcribed in the background.")),
                ('auto_admit', models.BooleanField(default=False, help_text='Let invited clients straight in once you have joined, instead of waiting for you to admit them.')),
                ('link_early_minutes', models.PositiveSmallIntegerField(default=30, help_text="How long before the start time a client's link starts working.")),
                ('link_late_hours', models.PositiveSmallIntegerField(default=3, help_text="How long after the start time a client's link keeps working.")),
                ('max_live_rooms', models.PositiveSmallIntegerField(default=4, help_text='Meetings that can run at the same time. Protects a small server; each room with an assistant uses roughly 300 MB.')),
                ('max_minutes', models.PositiveSmallIntegerField(default=90, help_text='A room still open after this long is closed automatically.')),
                ('interviewer_voice', models.CharField(blank=True, default='', help_text='Voice for the meeting agents. Blank uses the Azure Realtime voice.', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_agent', models.ForeignKey(blank=True, help_text='The prompt-based agent behind “Ask the assistant” in a meeting. Its prompt and, if it has one, its knowledge base are used.', limit_choices_to={'kind': 'prompt'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ConvAI.agent')),
            ],
            options={
                'verbose_name': 'Online meetings settings',
                'verbose_name_plural': 'Online meetings settings',
            },
        ),
        migrations.CreateModel(
            name='RecordingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=True)),
                ('notice_version', models.CharField(default='1', max_length=20)),
                ('notice_text', models.TextField(blank=True, default='')),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='meetings.meetinginvite')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=96)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('track_sid', models.CharField(max_length=64)),
                ('seq', models.PositiveIntegerField(default=0)),
                ('path', models.CharField(max_length=500)),
                ('codec', models.CharField(blank=True, default='ogg/opus', max_length=20)),
                ('start_utc_ms', models.BigIntegerField()),
                ('end_utc_ms', models.BigIntegerField(blank=True, null=True)),
                ('bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ['start_utc_ms', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'live')), fields=('meeting',), name='one_live_session_per_meeting'),
        ),
        migrations.AddConstraint(
            model_name='lobbyentry',
            constraint=models.UniqueConstraint(fields=('meeting', 'invite'), name='one_lobby_entry_per_invite'),
        ),
        migrations.AddConstraint(
            model_name='recordingsegment',
            constraint=models.UniqueConstraint(fields=('session', 'identity', 'track_sid', 'seq'), name='one_row_per_segment'),
        ),
    ]
