"""Web (non-API) routes: pages, forms, chat, Twilio media/webhook."""
from django.urls import path
from django.conf import settings
from django.contrib.auth.views import LogoutView

from .views import (
    dashboard, patient_list, RoleBasedLoginView, pending_call, help_page, help_edit,
    profile, update_profile, update_language, whatsapp_webhook, update_twilio_phonecalls,
    serve_protected_file, config, config_save, schedule_call,
    patient_detail, patient_conversation_detail, make_phone_call, complete_meeting,
    cancel_meeting,
    calendar_view, calendar_create_meeting, create_user, user_list, create_client,
    create_test_user, test_user_result, edit_user, edit_patient,
    add_note, edit_note, delete_note,
    agent_list, agent_form, agent_delete, agent_test, agent_test_send, agent_test_audio,
    agent_realtime_session, external_realtime_session,
    agent_knowledge, agent_knowledge_upload, agent_knowledge_status,
    agent_knowledge_toggle, agent_knowledge_delete, agent_knowledge_retry,
    edit_patient_details, edit_care_plan, view_care_plan,
    save_client_note, update_client_terms,
    toggle_patient_chatbot, raise_alert,
    hide_next_call,
    download_care_plan, edit_meeting, send_meeting_reminder_view,
    send_chat_message, protocol_view, protocol_editor,
    protocol_editor_save, protocol_create, protocol_delete, message_feedback,
    create_chat_link, external_chat, send_external_message, serve_audio_file,
    external_audio, process_audio, conversation_feedback, run_conversation_classification,
    issue_api_token, approve_self_registration, alert_detail, act_alert, send_alert_sms,
    send_test_email_view,
    PasswordResetRequestView, PasswordResetSentView,
    PasswordResetConfirmView, PasswordResetCompleteView,
    alerts_since,
    twilio_audio_download, send_care_plan_whatsapp, twilio_careplan_download,
    start_protocol_automation, dismiss_sms_offer, communications, panel_fragment,
    summarize_meeting_view, transcribe_recording_view, edit_overview,
    download_client_sdk,
)
from .utils import navigator_required, patient_tester_required

urlpatterns = [
    path('', navigator_required(dashboard), name='dashboard'),
    path('dashboard/next-call/hide/', navigator_required(hide_next_call), name='hide_next_call'),
    path('patients/', navigator_required(patient_list), name='patients'),
    path('patients/create/', navigator_required(create_client), name='create_client'),
    path('patients/<int:pk>/edit/', navigator_required(edit_patient), name='edit_patient'),
    path('users/', user_list, name='users'),
    path('users/create/', create_user, name='create_user'),
    path('users/create-test/', create_test_user, name='create_test_user'),
    path('users/test-result/', test_user_result, name='test_user_result'),
    path('users/<int:pk>/edit/', edit_user, name='edit_user'),
    path('agents/', agent_list, name='agents'),
    path('agents/new/<str:kind>/', agent_form, name='agent_create'),
    path('agents/<int:pk>/edit/', agent_form, name='agent_edit'),
    path('agents/<int:pk>/delete/', agent_delete, name='agent_delete'),
    path('agents/<int:pk>/test/', agent_test, name='agent_test'),
    path('agents/<int:pk>/test/send/', agent_test_send, name='agent_test_send'),
    path('agents/<int:pk>/test/audio/', agent_test_audio, name='agent_test_audio'),
    path('agents/<int:pk>/test/realtime-session/', agent_realtime_session, name='agent_realtime_session'),
    # Knowledge base for RAG-based prompt agents. Upload is one file per
    # request so each gets its own progress bar; everything else is polled
    # from the DB, so a reload picks up jobs already running.
    path('agents/<int:pk>/knowledge/', agent_knowledge, name='agent_knowledge'),
    path('agents/<int:pk>/knowledge/upload/', agent_knowledge_upload, name='agent_knowledge_upload'),
    path('agents/<int:pk>/knowledge/status/', agent_knowledge_status, name='agent_knowledge_status'),
    path('agents/<int:pk>/knowledge/<int:doc_id>/toggle/', agent_knowledge_toggle, name='agent_knowledge_toggle'),
    path('agents/<int:pk>/knowledge/<int:doc_id>/delete/', agent_knowledge_delete, name='agent_knowledge_delete'),
    path('agents/<int:pk>/knowledge/<int:doc_id>/retry/', agent_knowledge_retry, name='agent_knowledge_retry'),
    path('login/', RoleBasedLoginView.as_view(), name='login'),
    path('calls/<str:call_id>', navigator_required(pending_call), name='pending_call'),
    path('help/', navigator_required(help_page), name='help'),
    path('help/edit/', help_edit, name='help_edit'),
    path('profile/', navigator_required(profile), name='profile'),
    path('profile/update/', navigator_required(update_profile), name='update_profile'),
    path('profile/language/', navigator_required(update_language), name='update_language'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    # Password recovery. Django's flow, our templates and provider — see
    # ConvAI/views/account.py. The `reset/` paths keep Django's own shape so the
    # links in older emails, if any are still in flight, resolve.
    path('password-reset/', PasswordResetRequestView.as_view(), name='password_reset'),
    path('password-reset/sent/', PasswordResetSentView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # Inbound Twilio webhook: path is configurable via TWILIO_WEBHOOK_PATH.
    path(getattr(settings, 'TWILIO_WEBHOOK_PATH', 'webhooks/whatsapp'), whatsapp_webhook, name='whatsapp_webhook'),
    path('app/update_twilio', update_twilio_phonecalls, name='update_twilio'),
    path('app/config', navigator_required(config), name='config'),
    path('app/config/save', navigator_required(config_save), name='config_save'),
    path('app/protected/<str:id>/', navigator_required(serve_protected_file), name='serve_protected_file'),
    path('app/schedule_call', navigator_required(schedule_call), name='schedule_call'),
    path('patients/<int:pk>/', navigator_required(patient_detail), name='patient_detail'),
    path('patients/<int:pk>/conversations/<str:day>/', navigator_required(patient_conversation_detail), name='patient_conversation_detail'),
    path('meetings/<int:meeting_id>/call/', navigator_required(make_phone_call), name='make_phone_call'),
    path('meetings/<int:meeting_id>/complete/', navigator_required(complete_meeting), name='complete_meeting'),
    path('meetings/<int:meeting_id>/cancel/', navigator_required(cancel_meeting), name='cancel_meeting'),
    path('calendar/', navigator_required(calendar_view), name='calendar'),
    path('calendar/create/', navigator_required(calendar_create_meeting), name='calendar_create_meeting'),
    path('patients/<int:pk>/edit_details/', navigator_required(edit_patient_details), name='edit_patient_details'),
    path('patients/<int:pk>/note/', navigator_required(save_client_note), name='save_client_note'),
    path('patients/<int:pk>/terms/', navigator_required(update_client_terms), name='update_client_terms'),
    path('patients/<int:pk>/chatbot/', navigator_required(toggle_patient_chatbot), name='toggle_patient_chatbot'),
    path('patients/<int:pk>/raise-alert/', navigator_required(raise_alert), name='raise_alert'),

    # Notes on a call, meeting, alert or conversation. One set of endpoints for
    # all four; the kind in the path says which parent the note hangs off.
    path('notes/<str:kind>/<str:pk>/add/', navigator_required(add_note), name='add_note'),
    path('notes/<int:pk>/edit/', navigator_required(edit_note), name='edit_note'),
    path('notes/<int:pk>/delete/', navigator_required(delete_note), name='delete_note'),
    path('patients/<int:pk>/care_plan/edit/', navigator_required(edit_care_plan), name="edit_care_plan"),
    path('patients/<int:pk>/care_plan/view/', navigator_required(view_care_plan), name="view_care_plan"),
    path('patients/<int:pk>/care_plan/download/', navigator_required(download_care_plan), name='download_care_plan'),
    path('meetings/<int:meeting_id>/edit/', navigator_required(edit_meeting), name='edit_meeting'),
    path('meetings/<int:meeting_id>/send_reminder/', navigator_required(send_meeting_reminder_view), name='send_meeting_reminder'),
    # Old name for the same endpoint, from when WhatsApp was the only channel.
    path('meetings/<int:meeting_id>/send_whatsapp/', navigator_required(send_meeting_reminder_view), name='send_whatsapp_reminder'),
    path('meetings/<int:meeting_id>/summarize/', navigator_required(summarize_meeting_view), name='summarize_meeting'),
    path('recordings/<str:sid>/transcribe/', navigator_required(transcribe_recording_view), name='transcribe_recording'),
    path('summaries/<str:kind>/<str:pk>/edit/', navigator_required(edit_overview), name='edit_overview'),
    path('client-sdk/download/', download_client_sdk, name='download_client_sdk'),
    path('chat/send/', navigator_required(send_chat_message), name='send_chat_message'),
    path("meeting/<int:meeting_id>/protocol/<int:protocol_num>/", navigator_required(protocol_view), name="protocol_view"),
    path("protocols/<int:protocol_num>/editor/", navigator_required(protocol_editor), name="protocol_editor"),
    path("protocols/<int:protocol_num>/editor/save/", navigator_required(protocol_editor_save), name="protocol_editor_save"),
    path("protocols/create/", navigator_required(protocol_create), name="protocol_create"),
    path("protocols/<int:protocol_num>/delete/", navigator_required(protocol_delete), name="protocol_delete"),
    path('messages/<int:message_id>/feedback/', navigator_required(message_feedback), name='message_feedback'),
    path('chat/link/<int:patient_pk>/', patient_tester_required(create_chat_link), name='create_chat_link'),
    path("chat/external/", patient_tester_required(external_chat), name="external_chat"),
    path("chat/external/send/", patient_tester_required(send_external_message), name="send_external_message"),
    path("chat/external/realtime-session/", patient_tester_required(external_realtime_session), name="external_realtime_session"),
    # No role gate here: the view enforces per-object ownership itself
    # (admin → any; tester → own patient; navigator → their patients' audio).
    path('app/audio/<int:message_id>/<str:which>/', serve_audio_file, name='serve_audio_file'),
    path("chat/external/audio/", patient_tester_required(external_audio), name="external_audio"),
    path("chat/external/audio/process/", process_audio, name="process_audio"),
    path("conversations/<str:conversation_id>/feedback/", navigator_required(conversation_feedback), name="conversation_feedback"),
    path("config/run-classification/", run_conversation_classification, name="run_conversation_classification"),
    path("config/send-test-email/", send_test_email_view, name="send_test_email"),
    path("profile/token/issue/", issue_api_token, name="issue_api_token"),
    path('self-registrations/<int:pk>/approve/', approve_self_registration, name='approve_self_registration'),
    # Polled by the notification component in base.html.
    path("alerts/since/", alerts_since, name="alerts_since"),
    # The detail panel on its own, fetched by base.html when a row is opened so
    # the list beside it is not thrown away and rebuilt. Same guard as every
    # page that hosts a panel; the item itself is permission-checked again in
    # resolve_panel_item, as it is on a full page load.
    path("panel/", navigator_required(panel_fragment), name="panel_fragment"),
    path("alerts/<int:pk>/", alert_detail, name="alert_detail"),
    path("alerts/<int:pk>/act/", act_alert, name="act_alert"),
    path("alerts/<int:alert_id>/send-infection-sms/", send_alert_sms, name="send_alert_sms"),
    path("twilio/audio/<int:message_id>/<str:kind>/", twilio_audio_download, name="twilio_audio_download"),
    path("patients/<int:pk>/send-care-plan/", send_care_plan_whatsapp, name="send_care_plan_whatsapp"),
    path("twilio/documents/careplan_<int:pk>.pdf/", twilio_careplan_download, name="twilio_careplan_download"),
    path("meetings/<int:meeting_id>/protocol/<int:protocol_num>/automation/start/", start_protocol_automation, name="start_protocol_automation"),
    path("protocol/automation/sms-offer/dismiss/", dismiss_sms_offer, name="dismiss_sms_offer"),
    path("communications/", navigator_required(communications), name="communications"),
]
