# Generated by Django 5.1 on 2025-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("convesation_id", models.CharField(max_length=300)),
                ("user", models.CharField(max_length=300)),
                ("timestamp", models.DateTimeField()),
                ("message", models.CharField(max_length=300)),
                ("response", models.CharField(max_length=300)),
                ("input_audio", models.CharField(max_length=300)),
                ("response_audio", models.CharField(max_length=300)),
            ],
        ),
    ]
