# Generated by Django 5.1 on 2025-05-01 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0002_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp"]},
        ),
        migrations.RemoveField(
            model_name="message",
            name="convesation_id",
        ),
        migrations.RemoveField(
            model_name="message",
            name="input_audio",
        ),
        migrations.RemoveField(
            model_name="message",
            name="message",
        ),
        migrations.RemoveField(
            model_name="message",
            name="response",
        ),
        migrations.RemoveField(
            model_name="message",
            name="response_audio",
        ),
        migrations.AddField(
            model_name="message",
            name="conversation_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="response_message",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="user_message",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation_id", "user", "timestamp"],
                name="ConvAI_mess_convers_ee2d5b_idx",
            ),
        ),
    ]
