# Generated by Django 5.1 on 2025-05-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0003_alter_message_options_remove_message_convesation_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recording_sid", models.CharField(max_length=100)),
                ("from_number", models.CharField(max_length=100)),
                ("to_number", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("filename", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
