# Generated by Django 5.1 on 2025-05-13 14:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0004_callrecording"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caregiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("lastname", models.TextField()),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("lastname", models.TextField()),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "caregiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient",
                        to="ConvAI.caregiver",
                    ),
                ),
                (
                    "navigator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Regular"), (0, "Onboarding"), (2, "Final")],
                        default=1,
                        help_text="0 = Onboarding, 1 = Regular, 2 = Final",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Completed")],
                        default=0,
                        help_text="0 = pending, 1 = completed",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="ConvAI.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_time"],
            },
        ),
    ]
