# Generated by Django 5.1 on 2025-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0005_caregiver_patient_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="details",
            field=models.TextField(blank=True, help_text="Markdown"),
        ),
    ]
