# Generated by Django 5.1 on 2025-05-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0006_patient_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pendiente"),
                    (1, "Completada"),
                    (2, "Interrumpuda"),
                    (3, "No contestada"),
                ],
                default=0,
                help_text="0 = pending, 1 = completed",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Protocolo"),
                    (0, "Llamada 0"),
                    (2, "Final"),
                    (3, "Llamada 1"),
                ],
                default=1,
                help_text="0 = Onboarding, 1 = Regular, 2 = Final",
            ),
        ),
    ]
