# Generated by Django 5.1 on 2025-05-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0007_alter_meeting_status_alter_meeting_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="executed_protocol",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Protocolo 1"),
                    (2, "Protocolo 2"),
                    (3, "Protocolo 3"),
                    (4, "Protocolo 4"),
                    (5, "Protocolo 5"),
                    (6, "Protocolo 6"),
                    (7, "Protocolo 7"),
                    (8, "Protocolo 8"),
                    (9, "Llamada Final"),
                ],
                help_text="Protocolo ejecutado (1–8) o llamada final (9)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="retries",
            field=models.PositiveIntegerField(default=0, help_text="Retries"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="scheduled_protocol",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Protocolo 1"),
                    (2, "Protocolo 2"),
                    (3, "Protocolo 3"),
                    (4, "Protocolo 4"),
                    (5, "Protocolo 5"),
                    (6, "Protocolo 6"),
                    (7, "Protocolo 7"),
                    (8, "Protocolo 8"),
                    (9, "Llamada Final"),
                ],
                help_text="Protocolo programado (1–8) o llamada final (9)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pendiente"),
                    (1, "Completada"),
                    (2, "Interrumpida"),
                    (3, "No contestada"),
                ],
                default=0,
                help_text="0 = pending, 1 = completed, 2 = interrupted, 3 = not answered",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Protocolo"),
                    (0, "Llamada 0"),
                    (2, "Final"),
                    (3, "Llamada 1"),
                ],
                default=1,
                help_text="0 = Onboarding, 1 = Regular, 2 = Final, 3 = Initial",
            ),
        ),
    ]
