# Generated by Django 5.1 on 2025-06-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0008_meeting_executed_protocol_meeting_retries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="executed_protocol",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1. Evaluación de necesidades"),
                    (2, "2. Medicación"),
                    (3, "3. Gestión del comportamiento"),
                    (4, "4. Seguridad"),
                    (5, "5. Bienestar del cuidador"),
                    (6, "6. Planificación anticipada"),
                    (7, "7. Derivación"),
                    (8, "8. Comorbilidades"),
                    (9, "Llamada Final"),
                ],
                help_text="Protocolo ejecutado (1–8) o llamada final (9)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="scheduled_protocol",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1. Evaluación de necesidades"),
                    (2, "2. Medicación"),
                    (3, "3. Gestión del comportamiento"),
                    (4, "4. Seguridad"),
                    (5, "5. Bienestar del cuidador"),
                    (6, "6. Planificación anticipada"),
                    (7, "7. Derivación"),
                    (8, "8. Comorbilidades"),
                    (9, "Llamada Final"),
                ],
                help_text="Protocolo programado (1–8) o llamada final (9)",
                null=True,
            ),
        ),
    ]
