# Generated by Django 5.1 on 2025-06-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0009_alter_meeting_executed_protocol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="care_plan",
            field=models.FileField(
                blank=True,
                help_text="Sube aquí el Plan de Cuidado en PDF (máx. 5 MB).",
                null=True,
                upload_to="care_plans/",
            ),
        ),
    ]
