# Generated by Django 5.1 on 2025-06-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ConvAI", "0012_alter_meeting_executed_protocol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="executed_protocol",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1. Necesidades inmediatas"),
                    (2, "2. Medicación"),
                    (3, "3. Comorbilidades"),
                    (4, "4. Bienestar del cuidador"),
                    (5, "5. Comportamiento"),
                    (6, "6. Seguridad"),
                    (7, "7. Derivación"),
                    (8, "8. Planificación anticipada"),
                    (9, "Salida"),
                    (10, "Llamada 0"),
                ],
                help_text="Protocolo ejecutado (1–8) o llamada final (9)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="scheduled_protocol",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1. Necesidades inmediatas"),
                    (2, "2. Medicación"),
                    (3, "3. Comorbilidades"),
                    (4, "4. Bienestar del cuidador"),
                    (5, "5. Comportamiento"),
                    (6, "6. Seguridad"),
                    (7, "7. Derivación"),
                    (8, "8. Planificación anticipada"),
                    (9, "Salida"),
                    (10, "Llamada 0"),
                ],
                help_text="Protocolo programado (1–8) o llamada final (9)",
                null=True,
            ),
        ),
    ]
