# Generated by Django 5.1 on 2025-06-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0013_alter_meeting_executed_protocol_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Protocol",
                "verbose_name_plural": "Protocols",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "prompt_md",
                    models.TextField(help_text="Explicación / pregunta en Markdown"),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="ConvAI.protocol",
                    ),
                ),
            ],
            options={
                "ordering": ["protocol", "order"],
                "unique_together": {("protocol", "order")},
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField()),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="ConvAI.meeting",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="ConvAI.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question__order"],
                "unique_together": {("meeting", "question")},
            },
        ),
    ]
