# Generated by Django 5.1 on 2025-06-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0014_protocol_question_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="disliked",
            field=models.BooleanField(
                default=False, help_text="Usuario marcó no me gusta"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="liked",
            field=models.BooleanField(
                default=False, help_text="Usuario marcó me gusta"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="warning",
            field=models.BooleanField(
                default=False, help_text="Usuario marcó advertencia"
            ),
        ),
    ]
