# Generated by Django 5.1 on 2025-07-20 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0015_message_disliked_message_liked_message_warning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('host', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='agent',
            field=models.ForeignKey(blank=True, help_text="Which LangGraph agent will handle this patient's chat", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConvAI.agent'),
        ),
    ]
