# Generated by Django 5.1 on 2025-07-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0016_agent_patient_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='langgraph_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='host',
            field=models.CharField(max_length=100),
        ),
    ]
