# Generated by Django 5.1 on 2025-07-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0017_agent_langgraph_name_alter_agent_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_thread_id',
            field=models.CharField(blank=True, help_text='UUID4 of the active chat thread; resets on /quit', max_length=36, null=True),
        ),
    ]
