# Generated by Django 5.1 on 2025-07-24 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0018_patient_current_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tester_account',
            field=models.OneToOneField(blank=True, help_text="User in group 'PatientTester' linked to this patient", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
