# Generated by Django 5.1 on 2025-07-31 09:43

import ConvAI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0019_patient_tester_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='input_audio_file',
            field=models.FileField(blank=True, help_text='Original user audio (webm/…)', null=True, upload_to=ConvAI.models._audio_upload_to),
        ),
        migrations.AddField(
            model_name='message',
            name='response_audio_file',
            field=models.FileField(blank=True, help_text='TTS response MP3', null=True, upload_to=ConvAI.models._audio_upload_to),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='executed_protocol',
            field=models.IntegerField(blank=True, choices=[(1, '1. Protocol 1'), (2, '2. Protocol 2'), (3, '3. Protocol 3'), (4, '4. Protocol 4'), (5, '5. Protocol 5'), (6, '6. Protocol 6'), (7, '7. Protocol 7'), (8, '8. Protocol 8'), (9, 'Final call'), (10, 'Onboarding')], help_text='Protocolo ejecutado (1–8) o llamada final (9)', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_protocol',
            field=models.IntegerField(blank=True, choices=[(1, '1. Protocol 1'), (2, '2. Protocol 2'), (3, '3. Protocol 3'), (4, '4. Protocol 4'), (5, '5. Protocol 5'), (6, '6. Protocol 6'), (7, '7. Protocol 7'), (8, '8. Protocol 8'), (9, 'Final call'), (10, 'Onboarding')], help_text='Protocolo programado (1–8) o llamada final (9)', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Interrupted'), (3, 'Not answered')], default=0, help_text='0 = pending, 1 = completed, 2 = interrupted, 3 = not answered'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.IntegerField(choices=[(1, 'Protocol'), (0, 'Onboarding'), (2, 'Final'), (3, 'Initial')], default=1, help_text='0 = Onboarding, 1 = Regular, 2 = Final, 3 = Initial'),
        ),
    ]
