# Generated by Django 5.1 on 2025-08-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0020_message_input_audio_file_message_response_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, help_text='UUID4 string used by Message.conversation_id', max_length=300, unique=True)),
                ('user', models.TextField(blank=True, default='', help_text='Phone or identifier')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
    ]
