# Generated by Django 5.1 on 2025-08-15 12:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0021_conversation'),
    ]

    operations = [
        # Remove the old DB object if it exists, and delete the model from state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'DROP TABLE IF EXISTS "ConvAI_conversation" CASCADE;',
                    reverse_sql=None,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(name='Conversation'),
            ],
        ),

        # Recreate with UUID PK and the new schema
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('feedback', models.TextField(blank=True)),
            ],
            options={'ordering': ['-last_message_at']},
        ),
    ]