# Generated by Django 5.1 on 2025-08-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0022_remove_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dangerous',
            field=models.BooleanField(default=False, help_text='Usuario marcó dangerous'),
        ),
    ]
