# Generated by Django 5.1 on 2025-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0023_message_dangerous'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='analyzed',
            field=models.BooleanField(db_index=True, default=False, help_text='Has analysis been run?'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_important',
            field=models.BooleanField(db_index=True, default=False, help_text='Requires human attention?'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, help_text='Automatic short abstract'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.CharField(blank=True, help_text='Classification label/topic', max_length=120),
        ),
        migrations.AddField(
            model_name='conversation',
            name='visited',
            field=models.BooleanField(db_index=True, default=False, help_text='Has been reviewed in dashboard?'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_important', 'visited'], name='ConvAI_conv_is_impo_4fd837_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['analyzed'], name='ConvAI_conv_analyze_b0e637_idx'),
        ),
    ]
