# Generated by Django 5.1 on 2025-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0024_conversation_analyzed_conversation_analyzed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='abstract_instruction',
            field=models.CharField(blank=True, default='≤80 words summary, in the conversation language.', help_text='Instruction for producing the abstract.', max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='classification_role',
            field=models.TextField(blank=True, help_text="Role/persona to imitate for classification, e.g. 'A senior Peruvian nurse technician trained in dementia caregiver triage'."),
        ),
        migrations.AddField(
            model_name='agent',
            name='detectors',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object mapping detector label → instruction/prompt.'),
        ),
    ]
