# Generated by Django 5.1 on 2025-08-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0025_agent_abstract_instruction_agent_classification_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='auto_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Auto detector booleans keyed by label (produced by automatic classification).'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='human_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Human validation of detector booleans, keyed by the same labels.'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='ConvAI_conv_last_me_a138f6_idx'),
        ),
    ]
