# Generated by Django 5.1 on 2025-08-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0026_conversation_auto_flags_conversation_human_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConvAI.agent'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConvAI.patient'),
        ),
    ]
