# Generated by Django 5.1 on 2025-09-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0027_conversation_agent_conversation_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='convaiuser',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Optional default LangGraph agent for this user (used for testing/API).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_default_agent', to='ConvAI.agent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='classification_role',
            field=models.TextField(blank=True, help_text="Role/persona to imitate for classification, e.g. 'A senior Peruvian nurse technician trained in dementia caregiver triage'.Also, include instructions on when should this be considered important that a human reviews the conversation.\nContinue the frase 'You are ...'"),
        ),
    ]
