# Generated by Django 5.1 on 2025-09-14 20:16

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0028_convaiuser_agent_alter_agent_classification_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Arbitrary extra fields for this application')),
                ('state', models.IntegerField(choices=[(0, 'Registered'), (1, 'Approved')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='ConvAI_self_state_8cd632_idx')],
            },
        ),
    ]
