# Generated by Django 5.1 on 2025-09-19 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0029_selfregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'In Progress'), (2, 'Resolved')], default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data for the alert')),
                ('alert_type', models.IntegerField(choices=[(0, 'Default'), (1, 'Conversation'), (2, 'Event'), (3, 'API Registered')], default=0)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('last_action_ok', models.BooleanField(default=False)),
                ('last_action_status', models.IntegerField(blank=True, null=True)),
                ('last_action_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ConvAI_aler_status_cc0eed_idx'), models.Index(fields=['alert_type'], name='ConvAI_aler_alert_t_44a0a2_idx'), models.Index(fields=['-created_at'], name='ConvAI_aler_created_fc142e_idx')],
            },
        ),
    ]
