# Generated by Django 5.1 on 2025-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0030_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tts_voice_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
