# Generated by Django 5.1 on 2025-10-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0032_alert_created_by_alert_patient_alter_alert_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='abstract_instruction',
            field=models.CharField(blank=True, default='≤80 words summary, in the conversation language.', help_text='Instruction for producing the abstract.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='agent',
            name='classification_role',
            field=models.TextField(blank=True, help_text="Role/persona to imitate for classification, e.g. 'A senior Peruvian nurse technician trained in dementia caregiver triage'.Also, include instructions on when should this be considered important that a human reviews the conversation.\nContinue the frase 'You are ...'", max_length=4096),
        ),
    ]
