# Generated by Django 5.1 on 2025-11-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0033_alter_agent_abstract_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='details_editable',
            field=models.TextField(blank=True, help_text='Markdown'),
        ),
    ]
