# Generated by Django 5.1 on 2026-07-06 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0035_conversation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_meeting_steps', models.CharField(blank=True, choices=[('', 'Use .env default'), ('1', 'On'), ('0', 'Off')], default='', max_length=1)),
                ('enable_automations', models.CharField(blank=True, choices=[('', 'Use .env default'), ('1', 'On'), ('0', 'Off')], default='', max_length=1)),
                ('self_registration_enabled', models.CharField(blank=True, choices=[('', 'Use .env default'), ('1', 'On'), ('0', 'Off')], default='', max_length=1)),
                ('self_reg_agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('send_care_plan', models.CharField(blank=True, choices=[('', 'Use .env default'), ('1', 'On'), ('0', 'Off')], default='', max_length=1)),
                ('whatsapp_audio_enabled', models.CharField(blank=True, choices=[('', 'Use .env default'), ('1', 'On'), ('0', 'Off')], default='', max_length=1)),
                ('twilio_account_sid', models.CharField(blank=True, default='', max_length=255)),
                ('twilio_auth_token', models.CharField(blank=True, default='', max_length=255)),
                ('impact_phone', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{6,14}$', 'Enter a phone number in E.164 format, e.g. +447700900000.')])),
                ('openai_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('elevenlabs_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('elevenlabs_voice_id', models.CharField(blank=True, default='', max_length=255)),
                ('twilio_sms_from', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{6,14}$', 'Enter a phone number in E.164 format, e.g. +447700900000.')])),
                ('sms_template_start_infection_sid', models.CharField(blank=True, default='', max_length=34, validators=[django.core.validators.RegexValidator('^HX[0-9a-fA-F]{32}$', 'Must be a Twilio SID like HX + 32 hex characters.')])),
                ('sms_template_start_infection_text', models.TextField(blank=True, default='')),
                ('whatsapp_template_care_plan_sid', models.CharField(blank=True, default='', max_length=34, validators=[django.core.validators.RegexValidator('^HX[0-9a-fA-F]{32}$', 'Must be a Twilio SID like HX + 32 hex characters.')])),
                ('brand_name', models.CharField(blank=True, default='', max_length=255)),
                ('brand_logo', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
            },
        ),
        migrations.AlterField(
            model_name='meeting',
            name='executed_protocol',
            field=models.IntegerField(blank=True, choices=[(1, '1. Protocol 1'), (2, '2. Protocol 2'), (3, '3. Protocol 3'), (4, '4. Protocol 4'), (5, '5. Protocol 5'), (6, '6. Protocol 6'), (7, '7. Protocol 7'), (8, '8. Protocol 8'), (9, '9. Final call'), (10, '10. Follow-up')], help_text='Protocolo ejecutado (1–8) o llamada final (9)', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_protocol',
            field=models.IntegerField(blank=True, choices=[(1, '1. Protocol 1'), (2, '2. Protocol 2'), (3, '3. Protocol 3'), (4, '4. Protocol 4'), (5, '5. Protocol 5'), (6, '6. Protocol 6'), (7, '7. Protocol 7'), (8, '8. Protocol 8'), (9, '9. Final call'), (10, '10. Follow-up')], help_text='Protocolo programado (1–8) o llamada final (9)', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.IntegerField(choices=[(1, 'Protocol'), (0, 'Onboarding'), (2, 'Final'), (3, 'Initial'), (4, 'Follow-up')], default=1, help_text='0 = Onboarding, 1 = Regular, 2 = Final, 3 = Initial'),
        ),
    ]
