# Generated by Django 5.1 on 2026-07-06 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0036_siteconfiguration_alter_meeting_executed_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='brand_logo_file',
            field=models.FileField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp', 'gif'])]),
        ),
    ]
