# Generated by Django 5.1 on 2026-07-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0037_siteconfiguration_brand_logo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='convaiuser',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('es-pe', 'Español (Perú)'), ('pt-br', 'Português (Brasil)'), ('en-gb', 'English (UK)')], default='', help_text='Preferred interface language; blank uses the system default.', max_length=10),
        ),
    ]
