# Generated by Django 5.1 on 2026-07-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0040_rename_siteconfiguration_impact_phone_platform_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'permissions': [('access_configuration', 'Can access configuration')], 'verbose_name': 'Site configuration'},
        ),
    ]
