# Generated by Django 5.1 on 2026-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0042_seed_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='kind',
            field=models.CharField(choices=[('remote', 'Remote'), ('native', 'Native')], db_index=True, default='remote', help_text='Remote = runs on a LangGraph server (host:port). Native = ships with the platform and runs in-process.', max_length=16),
        ),
        migrations.AddField(
            model_name='agent',
            name='native_key',
            field=models.CharField(blank=True, default='', help_text="For native agents: which built-in graph to run (e.g. 'loopback', 'link_worker').", max_length=64),
        ),
        migrations.AlterField(
            model_name='agent',
            name='host',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='langgraph_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
