# Generated by Django 5.1 on 2026-07-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0044_seed_native_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='System prompt for prompt-based agents. Used as the system message on every turn.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='kind',
            field=models.CharField(choices=[('remote', 'Remote'), ('native', 'Native'), ('prompt', 'Prompt-based')], db_index=True, default='remote', help_text='Remote = runs on a LangGraph server (host:port). Native = ships with the platform. Prompt-based = in-process agent driven by a stored prompt.', max_length=16),
        ),
    ]
