# Generated by Django 5.1 on 2026-07-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0045_agent_system_prompt_alter_agent_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="help_markdown",
            field=models.TextField(blank=True, default=""),
        ),
    ]
