# Generated by Django 5.1 on 2026-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0046_siteconfiguration_help_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="agent_allowed_hosts",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated list of allowed agent hosts",
            ),
        ),
    ]
