# Generated by Django 5.1 on 2026-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0047_siteconfiguration_agent_allowed_hosts"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Model behind this agent, e.g. 'openai/gpt-4.1-mini' or 'anthropic/claude-sonnet-4-6'. Blank uses the platform default. Not used by remote agents.",
                max_length=200,
            ),
        ),
    ]
