# Generated by Django 5.1 on 2026-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0048_agent_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="anthropic_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_anthropic_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_anthropic_endpoint",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_deepseek_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_deepseek_endpoint",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_mistral_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_mistral_endpoint",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_openai_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_openai_api_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_openai_endpoint",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="deepseek_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="default_agent_model",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="google_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="mistral_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="use_azure",
            field=models.CharField(
                blank=True,
                choices=[("", "Use .env default"), ("1", "On"), ("0", "Off")],
                default="",
                max_length=1,
            ),
        ),
    ]
