# Generated by Django 5.1 on 2026-07-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0049_siteconfiguration_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='transcribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='transcript',
            field=models.TextField(blank=True, default='', help_text='Whisper transcription of the call audio'),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='transcript_summary',
            field=models.TextField(blank=True, default='', help_text='LLM summary of the transcript'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='protocol_summarized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='protocol_summary',
            field=models.TextField(blank=True, default='', help_text="LLM summary of this meeting's protocol answers"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meeting_summary_prompt',
            field=models.TextField(blank=True, default='', help_text="Base prompt for summarizing a meeting's protocol answers"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='transcript_summary_prompt',
            field=models.TextField(blank=True, default='', help_text='Base prompt for summarizing a call transcript'),
        ),
    ]
