# Generated by Django 5.1 on 2026-07-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0053_seed_self_registration_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convaiuser',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('es-pe', 'Español (Perú)'), ('pt-br', 'Português (Brasil)'), ('en-gb', 'English (UK)'), ('it', 'Italiano'), ('ko', '한국어'), ('zh-hans', '简体中文')], default='', help_text='Preferred interface language; blank uses the system default.', max_length=10),
        ),
    ]
