# Generated by Django 5.1 on 2026-07-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0054_alter_convaiuser_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='realtime_enabled',
            field=models.BooleanField(default=False, help_text='Prompt-based agents only: chat through the real-time voice API (live speech in/out) instead of the text chat.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='azure_realtime_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='azure_realtime_deployment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='azure_realtime_endpoint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='azure_realtime_voice',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
