# Generated by Django 5.1 on 2026-07-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0055_agent_realtime_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='azure_realtime_webrtc_region',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
