# Generated by Django 5.1 on 2026-08-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0056_siteconfiguration_azure_realtime_webrtc_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.TextField(blank=True, default='', help_text="Navigator's own notes for this call"),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notes_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
