# Generated by Django 5.1 on 2026-08-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0057_meeting_notes_meeting_notes_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, help_text='Where an in-person meeting takes place', max_length=200),
        ),
        migrations.AddField(
            model_name='meeting',
            name='modality',
            field=models.IntegerField(choices=[(0, 'Phone call'), (1, 'In person')], default=0, help_text='Phone call or in-person meeting'),
        ),
    ]
