# Generated by Django 5.1 on 2026-08-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0058_meeting_location_meeting_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='involvement',
            field=models.CharField(blank=True, help_text='How involved they usually are — for example, usually on the call', max_length=120),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='relationship',
            field=models.CharField(blank=True, help_text='How they are related to the client — daughter, neighbour, paid carer', max_length=60),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_terms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
