# Generated by Django 5.1 on 2026-08-05 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0059_caregiver_involvement_caregiver_relationship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('is_standard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_terms_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_standard', 'label'],
            },
        ),
    ]
