# Generated by Django 5.1 on 2026-08-06 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0061_seed_contact_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'token'], name='ConvAI_seen_user_id_0969ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'token'), name='seenmark_once_per_user')],
            },
        ),
    ]
