# Generated by Django 5.1 on 2026-08-06 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0062_seenmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chatbot_enabled',
            field=models.BooleanField(default=True, help_text="When off, the agent stops replying to this client's messages."),
        ),
        migrations.AddField(
            model_name='patient',
            name='chatbot_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='chatbot_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbots_disabled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='chatbot_off_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
