# Generated by Django 5.1 on 2026-08-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0063_patient_chatbot_enabled_patient_chatbot_off_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convaiuser',
            name='dashboard_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
