# Generated by Django 5.1 on 2026-08-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0064_convaiuser_dashboard_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Interrupted'), (3, 'Not answered'), (4, 'Cancelled')], default=0, help_text='0 = pending, 1 = completed, 2 = interrupted, 3 = not answered'),
        ),
    ]
