# Generated by Django 5.1 on 2026-08-20 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0065_meeting_cancel_reason_meeting_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='transcript_moments',
            field=models.JSONField(blank=True, default=list, help_text='Key moments, each anchored to a segment'),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='transcript_segments',
            field=models.JSONField(blank=True, default=list, help_text='Whisper segments: start, end, text, speaker'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='transcript_moments_prompt',
            field=models.TextField(blank=True, default='', help_text='Base prompt for pulling key moments out of a call transcript'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='ConvAI.alert')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_written', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='ConvAI.conversation')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='ConvAI.meeting')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='ConvAI.callrecording')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ConvAI_note_created_408b42_idx')],
            },
        ),
    ]
