# Generated by Django 5.1 on 2026-08-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0068_alert_internal_note_to_note_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='by_text',
            field=models.BooleanField(default=False, help_text='True when the protocol_qa automation captured this from a message'),
        ),
    ]
