# Generated by Django 5.1 on 2026-08-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConvAI", "0073_rag_agents"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_email_access_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_email_connection_string",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="azure_email_endpoint",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_from",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_from_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Use .env default"),
                    ("azure", "Azure Communication Services"),
                    ("smtp", "SMTP"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_reply_to",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="reminder_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Use .env default"),
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="smtp_host",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="smtp_password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="smtp_port",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="smtp_security",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Use .env default"),
                    ("tls", "STARTTLS (port 587)"),
                    ("ssl", "SSL/TLS (port 465)"),
                    ("none", "None"),
                ],
                default="",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="smtp_user",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
