# Generated by Django 5.1 on 2026-08-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0075_seed_iqcode_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='executed_protocols',
            field=models.ManyToManyField(blank=True, help_text='Protocols actually covered, recorded when the call is closed.', related_name='executed_meetings', to='ConvAI.protocol'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='scheduled_protocols',
            field=models.ManyToManyField(blank=True, help_text='Protocols this call is booked to address.', related_name='scheduled_meetings', to='ConvAI.protocol'),
        ),
        migrations.AddField(
            model_name='patient',
            name='protocols',
            field=models.ManyToManyField(blank=True, help_text='Protocols this client works through. Shown in their call panel.', related_name='patients', to='ConvAI.protocol'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='repeatable',
            field=models.BooleanField(default=False, help_text='This protocol is answered again on later calls, each call its own round.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='executed_protocol',
            field=models.IntegerField(blank=True, choices=[(1, '1. Protocol 1'), (2, '2. Protocol 2'), (3, '3. Protocol 3'), (4, '4. Protocol 4'), (5, '5. Protocol 5'), (6, '6. Protocol 6'), (7, '7. Protocol 7'), (8, '8. Protocol 8'), (9, '9. Final call'), (10, '10. Follow-up')], help_text='Deprecated — superseded by executed_protocols.', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_protocol',
            field=models.IntegerField(blank=True, choices=[(1, '1. Protocol 1'), (2, '2. Protocol 2'), (3, '3. Protocol 3'), (4, '4. Protocol 4'), (5, '5. Protocol 5'), (6, '6. Protocol 6'), (7, '7. Protocol 7'), (8, '8. Protocol 8'), (9, '9. Final call'), (10, '10. Follow-up')], help_text='Deprecated — superseded by scheduled_protocols.', null=True),
        ),
    ]
