# Generated by Django 5.1 on 2026-08-26 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0077_backfill_protocol_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_edits', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_edit', to='ConvAI.conversation')),
                ('meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_edit', to='ConvAI.meeting')),
                ('recording', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_edit', to='ConvAI.callrecording')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
