# Generated by Django 5.1 on 2026-08-26 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0079_summaryedit_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='call_sid',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Twilio's Call SID — the join back to the leg that was placed.", max_length=64),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='leg',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Client side'), (1, 'Navigator side')], help_text='Which side of the conference this recording is of.', null=True),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='meeting',
            field=models.ForeignKey(blank=True, help_text='The call this recording came from, where it is known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='ConvAI.meeting'),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Whose recording this is. Kept alongside the meeting rather than read through it, so a call placed outside a meeting still has an owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='ConvAI.patient'),
        ),
        migrations.CreateModel(
            name='CallLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(help_text="Twilio's Call SID for this leg.", max_length=64, unique=True)),
                ('leg', models.SmallIntegerField(choices=[(0, 'Client side'), (1, 'Navigator side')])),
                ('to_number', models.CharField(blank=True, default='', max_length=100)),
                ('conference_name', models.CharField(blank=True, default='', max_length=64)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='ConvAI.meeting')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_legs', to='ConvAI.patient')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_legs_placed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
    ]
