# Generated by Django 5.1 on 2026-09-27 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0088_agent_summary_and_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='allow_callbacks',
            field=models.BooleanField(default=False, help_text="Remote agents only: give each run a short-lived token that lets the agent report a summary and set the conversation's visibility, for that one conversation only."),
        ),
        migrations.AddField(
            model_name='message',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Login this message came through, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Client this message belongs to, fixed when it was written.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ConvAI.patient'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('caregiver', 'Caregiver'), ('staff', 'Staff'), ('tester', 'Tester'), ('api', 'API account'), ('prospect', 'Prospective client'), ('platform', 'Platform'), ('', 'Unknown')], default='', help_text='Who wrote the inbound side, decided when the message arrived.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['patient', 'timestamp'], name='message_patient_ts_idx'),
        ),
    ]
