# Generated by Django 5.1 on 2026-09-28 19:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0090_backfill_message_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enrolment_auto_approve',
            field=models.CharField(blank=True, choices=[('', 'Use .env default'), ('1', 'On'), ('0', 'Off')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enrolment_code_attempt_limit',
            field=models.PositiveSmallIntegerField(default=10, help_text='Wrong access-code attempts allowed per address per hour before a lockout.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enrolment_code_words',
            field=models.PositiveSmallIntegerField(default=3, help_text='Words per participant access code (2-4). Three is usually right.', validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enrolment_landing_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enrolment_require_dob',
            field=models.CharField(blank=True, choices=[('', 'Use .env default'), ('1', 'On'), ('0', 'Off')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='study_enrolment_enabled',
            field=models.CharField(blank=True, choices=[('', 'Use .env default'), ('1', 'On'), ('0', 'Off')], default='', max_length=1),
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Short identifier used in URLs and exports, e.g. 'health-coach'.", unique=True)),
                ('display_name', models.CharField(help_text="Full name shown to participants, e.g. 'Health Coaching Waitlist Study'.", max_length=200)),
                ('is_open', models.BooleanField(default=True, help_text='When off, existing participants continue but no new enrolments are accepted.')),
                ('pis_url', models.URLField(blank=True, default='', help_text='Link to the Participant Information Sheet.')),
                ('consent_version', models.CharField(default='1.0', help_text='Version shown to participants and stored on every consent record.', max_length=20)),
                ('consent_intro', models.TextField(blank=True, default='', help_text='The paragraph shown above the consent tick-boxes.')),
                ('consent_items', models.JSONField(blank=True, default=list, help_text='The tick-boxes themselves: a list of {key, text, required}.')),
                ('consent_survey_url', models.URLField(blank=True, default='', help_text='Optional survey to send the participant to straight after consent.')),
                ('baseline_url', models.URLField(blank=True, default='', help_text='Optional baseline questionnaire, after the consent survey.')),
                ('require_phone', models.BooleanField(default=False, help_text='Require a phone number to claim a code. Needed for SMS or WhatsApp arms.')),
                ('chief_investigator', models.CharField(blank=True, default='', max_length=200)),
                ('iras_project_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_agent', models.ForeignKey(blank=True, help_text="Agent given to this study's participants when they consent. Without one, their messages get no reply.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='ConvAI.agent')),
            ],
            options={
                'verbose_name_plural': 'Studies',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(db_index=True, help_text='The code the participant uses to claim their place. Single use.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('consented', 'Consented'), ('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], db_index=True, default='invited', max_length=12)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolment', to='ConvAI.patient')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='ConvAI.study')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='convaiuser',
            name='study',
            field=models.ForeignKey(blank=True, help_text="Limit this user to one study's participants. Blank sees all studies.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='ConvAI.study'),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_version', models.CharField(max_length=20)),
                ('items', models.JSONField(default=dict)),
                ('items_text', models.JSONField(blank=True, default=dict)),
                ('agreed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='ConvAI.enrolment')),
            ],
            options={
                'ordering': ['-agreed_at'],
                'indexes': [models.Index(fields=['enrolment', '-agreed_at'], name='ConvAI_cons_enrolme_d98e29_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['study', 'status'], name='ConvAI_enro_study_i_d40e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['-created_at'], name='ConvAI_enro_created_d8a1e4_idx'),
        ),
    ]
