# Generated by Django 5.1 on 2026-09-30 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# The v2 agent's row, so the Agents page lists it and Settings -> Agents can hand
# it the chat bubble. Seeded like the other natives (0044, descriptions in 0082);
# the description is held to the card's 90-character budget.
V2 = {
    "name": "Link Worker v2 (beta)",
    "kind": "native",
    "native_key": "link_worker_v2",
    "description": "Answers questions about clients' meetings, protocols and records, and books meetings.",
}


def seed_v2(apps, schema_editor):
    Agent = apps.get_model("ConvAI", "Agent")
    if not Agent.objects.filter(kind="native", native_key=V2["native_key"]).exists():
        Agent.objects.create(**V2)


def unseed_v2(apps, schema_editor):
    Agent = apps.get_model("ConvAI", "Agent")
    Agent.objects.filter(kind="native", native_key=V2["native_key"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0091_study_enrolment'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='link_worker_v2_enabled',
            field=models.CharField(blank=True, choices=[('', 'Use .env default'), ('1', 'On'), ('0', 'Off')], default='', max_length=1),
        ),
        migrations.CreateModel(
            name='RecordAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_label', models.CharField(blank=True, max_length=150)),
                ('patient_label', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('find', 'Find clients'), ('overview', 'Client overview'), ('meetings', 'Upcoming meetings'), ('answers', 'Protocol answers'), ('history', 'Protocol history'), ('search', 'Record search')], max_length=16)),
                ('via', models.CharField(choices=[('agent', 'Assistant'), ('api', 'API')], max_length=8)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_accesses', to='ConvAI.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'verbose_name': 'Record access',
                'verbose_name_plural': 'Record accesses',
                'indexes': [models.Index(fields=['patient', '-at'], name='ConvAI_reco_patient_b1cc6f_idx'), models.Index(fields=['user', '-at'], name='ConvAI_reco_user_id_433012_idx')],
            },
        ),
        migrations.RunPython(seed_v2, unseed_v2),
    ]
