# Generated by Django 5.1 on 2026-09-30 23:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0092_link_worker_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='link_worker_voice_pt_br',
            field=models.CharField(blank=True, default='', help_text="ElevenLabs voice ID used when a link worker's voice note is in Portuguese.", max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='link_worker_whatsapp_enabled',
            field=models.CharField(blank=True, choices=[('', 'Use .env default'), ('1', 'On'), ('0', 'Off')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='recordaccess',
            name='action',
            field=models.CharField(choices=[('find', 'Find clients'), ('load', 'Load a client'), ('overview', 'Client overview'), ('meetings', 'Upcoming meetings'), ('answers', 'Protocol answers'), ('history', 'Protocol history'), ('search', 'Record search')], max_length=16),
        ),
        migrations.AlterField(
            model_name='recordaccess',
            name='via',
            field=models.CharField(choices=[('agent', 'Assistant'), ('api', 'API'), ('whatsapp', 'WhatsApp')], max_length=8),
        ),
        migrations.CreateModel(
            name='StaffWhatsAppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('code_hash', models.CharField(blank=True, default='', max_length=128)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('code_tries', models.PositiveSmallIntegerField(default=0)),
                ('thread_id', models.CharField(blank=True, default='', max_length=36)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loaded_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ConvAI.patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff WhatsApp link',
                'verbose_name_plural': 'Staff WhatsApp links',
            },
        ),
    ]
