# Generated by Django 5.1 on 2026-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0093_link_worker_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='azure_voice',
            field=models.CharField(blank=True, default='', help_text='Azure AI Speech voice name, used when Azure is the TTS provider.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='azure_speech_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='azure_speech_region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='azure_speech_voice',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='link_worker_azure_voice_pt_br',
            field=models.CharField(blank=True, default='', help_text="Azure voice name used when a link worker's voice note is in Portuguese.", max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tts_provider',
            field=models.CharField(blank=True, choices=[('', 'Use .env default'), ('elevenlabs', 'ElevenLabs'), ('azure', 'Azure AI Speech')], default='', max_length=20),
        ),
    ]
