# Generated by Django 5.1 on 2026-10-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0094_text_to_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='starts_hidden',
            field=models.BooleanField(default=False, help_text="Remote agents with callbacks: each conversation starts hidden from the client's link worker, and the agent unhides it if the client agrees."),
        ),
    ]
