# Generated by Django 5.1 on 2026-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0095_agent_starts_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='summary_model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
