# Generated by Django 5.1 on 2026-10-08 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

def backfill_answer_source(apps, schema_editor):
    """Answers the WhatsApp automation captured were marked by_text; say so in source."""
    Answer = apps.get_model("ConvAI", "Answer")
    Answer.objects.filter(by_text=True).update(source="text")


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0096_summary_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kinds', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='source',
            field=models.CharField(choices=[('navigator', 'Navigator'), ('text', 'By text'), ('voice', 'By voice')], default='navigator', max_length=12),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'Phone (Twilio)'), (1, 'Online meeting')], default=0),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='speakers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='tracks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='from_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='to_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='modality',
            field=models.IntegerField(choices=[(0, 'Phone call'), (1, 'In person'), (2, 'Online meeting')], default=0, help_text='Phone call or in-person meeting'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ref', models.CharField(blank=True, db_index=True, default='', max_length=96)),
                ('dedupe_key', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('priority', models.SmallIntegerField(default=0)),
                ('run_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('locked_by', models.CharField(blank=True, default='', max_length=128)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'run_after', 'priority'], name='ConvAI_job_status_973caf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('dedupe_key',), name='job_live_dedupe_key')],
            },
        ),
        migrations.RunPython(backfill_answer_source, migrations.RunPython.noop),
    ]
