# Generated by Django 5.1 on 2026-10-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvAI', '0098_siteconfiguration_phone_calls_enabled'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('account__isnull', True), ('patient__isnull', True), ('sender_role', '')), fields=['user'], name='message_legacy_user_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('account__isnull', True), ('patient__isnull', True), ('sender_role', '')), fields=['conversation_id'], name='message_legacy_conv_idx'),
        ),
    ]
