"""
Django settings for Django_CMS project.

Generated by 'djangocms' command using django CMS 4.1.4 and Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of Django settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/

For the list of django CMS settings and their values, see
https://docs.django-cms.org/en/release-4.1.x/reference/configuration.html
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in .env for any real deployment; the fallback below is
# for local development only.
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    'django-insecure-4w&o+87te!5_=t$naft_%!ka6f-&@0%c9o3%lugce6*med(#ue',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Deployment hosts are configured via ALLOWED_HOSTS in .env (see settings_app.py).
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

CSRF_TRUSTED_ORIGINS = [
    'https://4560-20-68-249-158.ngrok-free.app',
    'https://conversational-care.ai',
    'https://www.conversational-care.ai'
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'djangocms_admin_style',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
     # CMS base apps
    # 'cms', #commenting cms as is not really used right now
    'menus',

    #'djangocms_text',
    #'djangocms_alias',
    #'djangocms_versioning',

    'sekizai',
    'treebeard',
    'parler',

    'filer',
    'easy_thumbnails',
    #'djangocms_frontend',
    #'djangocms_frontend.contrib.accordion',
    #'djangocms_frontend.contrib.alert',
    #'djangocms_frontend.contrib.badge',
    #'djangocms_frontend.contrib.card',
    #'djangocms_frontend.contrib.carousel',
    #'djangocms_frontend.contrib.collapse',
    #'djangocms_frontend.contrib.content',
    #'djangocms_frontend.contrib.grid',
    #'djangocms_frontend.contrib.icon',
    #'djangocms_frontend.contrib.image',
    #'djangocms_frontend.contrib.jumbotron',
    #'djangocms_frontend.contrib.link',
    #'djangocms_frontend.contrib.listgroup',
    #'djangocms_frontend.contrib.media',
    #'djangocms_frontend.contrib.navigation',
    #'djangocms_frontend.contrib.tabs',
    #'djangocms_frontend.contrib.utilities',

    #Apps
    'ConvAI',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'ConvAI.middleware.UserLanguageMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'cms.middleware.user.CurrentUserMiddleware',
    #'cms.middleware.page.CurrentPageMiddleware',
    #'cms.middleware.toolbar.ToolbarMiddleware',
    
    #'cms.middleware.language.LanguageCookieMiddleware',
]

ROOT_URLCONF = 'Django_CMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ConvAI/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
            ],
        },
    },
]

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

WSGI_APPLICATION = 'Django_CMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-gb'

LANGUAGES = [
    ("es-pe", _("Spanish")),
    ("pt-br", _("Portuguese")),
    ("en-gb", _("English")),
    ("it", _("Italian")),
    ("ko", _("Korean")),
    ("zh-hans", _("Chinese (Simplified)")),

    # Add additional languages here
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# Expose the REST API (ConvAI/api/urls.py). Set ENABLE_API=0 to disable it for
# deployments that don't want a public API.
ENABLE_API = os.getenv("ENABLE_API", "1").strip().lower() in ("1", "true", "yes", "on")

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_THOUSAND_SEPARATOR = False

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# This is a django CMS 4 template

CMS_CONFIRM_VERSION4 = True

# django CMS requires the site framework
# https://docs.django-cms.org/en/release-4.1.x/how_to/multi-site.html

SITE_ID = 1

# A base template is part of this setup
# https://docs.django-cms.org/en/release-4.1.x/reference/configuration.html#cms-templates

CMS_TEMPLATES = (
    ("base.html", _("Standard")),
    ("minimal.html", ("Minimal template")),
)

# Enable permissions
# https://docs.django-cms.org/en/release-4.1.x/topics/permissions.html

CMS_PERMISSION = True

# Allow admin sidebar to open admin URLs

X_FRAME_OPTIONS = 'SAMEORIGIN'

# Enable inline editing with djangocms-text
# https://github.com/django-cms/djangocms-text#inline-editing-feature

TEXT_INLINE_EDITING = True

# Allow deletion of version objects
# https://djangocms-versioning.readthedocs.io/en/latest/settings.html#DJANGOCMS_VERSIONING_ALLOW_DELETING_VERSIONS

DJANGOCMS_VERSIONING_ALLOW_DELETING_VERSIONS = True

# Add project-wide static files directory
# https://docs.djangoproject.com/en/5.1/ref/settings/#staticfiles-dirs

STATICFILES_DIRS = [
    BASE_DIR / "Django_CMS" / "static",
]

INTERNAL_IPS = [
    "127.0.0.1",
]

# Add project-wide static files directory
# https://docs.djangoproject.com/en/5.1/ref/settings/#media-root

MEDIA_URL = "media/"
MEDIA_ROOT = str(BASE_DIR.parent / "media")

# --- File storage layout (see file_storage.md) ------------------------------
# Everything lives on the persistent MEDIA_ROOT volume, organised by category.
# Only `branding/` is served publicly (the logo appears on the login page);
# every other directory below is PRIVATE and must never be served directly by
# the web server. Access is always mediated by ownership-checked views or by
# short-lived, single-use signed tokens (for Twilio-fetched WhatsApp media).
#
#   media/
#     branding/          public  — brand logo (login page)
#     care_plans/        private — uploaded care-plan PDFs
#     voice/             private — ElevenLabs TTS + inbound user voice notes
#     call_recordings/   private — call recordings downloaded from Twilio
#
# Paths are overridable via env for deployments that mount storage elsewhere.
VOICE_RECORDINGS_DIR = os.getenv("VOICE_RECORDINGS_DIR") or os.path.join(MEDIA_ROOT, "voice")
CALL_RECORDINGS_DIR = os.getenv("CALL_RECORDINGS_DIR") or os.path.join(MEDIA_ROOT, "call_recordings")

AUTH_USER_MODEL = "ConvAI.ConvAIUser"